version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # chat-server:
  #   build: ./server
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./server:/app

volumes:
  mysql_data:
